// apps/web/src/components/ui/ActionButton.tsx
import type { ActionButtonProps } from "@/types";
import { cn } from "@/utils";

/**
 * Action button component with variants
 * Converted from Vue ActionButton.vue
 */
export function ActionButton({
    icon,
    label,
    variant = "secondary",
    size = "md",
    onClick,
    disabled = false,
    className,
    loading = false,
    iconPosition = "left",
}: ActionButtonProps) {
    const baseClasses =
        "inline-flex items-center justify-center font-medium rounded-lg transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed";

    const variantClasses = {
        primary:
            "bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500 dark:bg-blue-500 dark:hover:bg-blue-600",
        secondary:
            "bg-gray-100 text-gray-900 hover:bg-gray-200 focus:ring-gray-500 dark:bg-gray-700 dark:text-gray-100 dark:hover:bg-gray-600",
        danger:
            "bg-red-600 text-white hover:bg-red-700 focus:ring-red-500 dark:bg-red-500 dark:hover:bg-red-600",
    };

    const sizeClasses = {
        sm: "px-3 py-2 text-sm",
        md: "px-4 py-2 text-sm",
        lg: "px-6 py-3 text-base",
    };

    const content = (
        <>
            {icon && iconPosition === "left" && (
                <span className="text-lg mr-2" aria-hidden>
                    {icon}
                </span>
            )}
            <span>{label}</span>
            {icon && iconPosition === "right" && (
                <span className="text-lg ml-2" aria-hidden>
                    {icon}
                </span>
            )}
            {loading && (
                <span
                    className="ml-2 inline-block h-4 w-4 animate-spin rounded-full border-2 border-current border-r-transparent align-middle"
                    aria-hidden
                />
            )}
        </>
    );
    return (
        <button
            type="button"
            onClick={!loading ? onClick : undefined}
            aria-disabled={disabled || loading}
            disabled={disabled || loading}
            className={cn(
                baseClasses,
                variantClasses[variant],
                sizeClasses[size],
                loading && "opacity-80 cursor-progress",
                className,
            )}
        >
            {content}
        </button>
    );
}

// legacy/frontend-vue/src/components/ActionButton.vue
<script setup lang="ts">
import { computed } from 'vue';

interface Props {
  variant?: 'primary' | 'secondary' | 'danger' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
  icon?: object | string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  size: 'md',
  type: 'button',
  disabled: false,
  icon: undefined,
});

defineEmits<{
  click: [event: MouseEvent];
}>();

const sizeClasses = computed(() => {
  const sizes = {
    sm: 'px-3 py-1.5 text-xs',
    md: 'px-4 py-2 text-sm',
    lg: 'px-6 py-3 text-base',
  };
  return sizes[props.size];
});

const variantClasses = computed(() => {
  const variants = {
    primary:
      'bg-blue-600 text-white border-blue-600 focus:ring-blue-500 hover:bg-blue-700',
    secondary:
      'bg-gray-100 text-gray-900 border-gray-300 focus:ring-gray-500 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-100 dark:border-gray-600 dark:hover:bg-gray-600',
    danger:
      'bg-red-600 text-white border-red-600 focus:ring-red-500 hover:bg-red-700',
    ghost:
      'bg-transparent text-gray-700 border-gray-300 focus:ring-gray-500 hover:bg-gray-50 dark:text-gray-300 dark:border-gray-600 dark:hover:bg-gray-800',
  };
  return variants[props.variant];
});
</script>

<template>
  <button
    :type="type"
    :disabled="disabled"
    class="inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors duration-200"
    :class="[
      sizeClasses,
      variantClasses,
      disabled ? 'opacity-50 cursor-not-allowed' : 'hover:opacity-90',
    ]"
    @click="$emit('click', $event)"
  >
    <component
      :is="icon"
      v-if="icon"
      class="w-4 h-4"
      :class="{ 'mr-2': !!$slots.default }"
    />
    <slot />
  </button>
</template>
