// apps/web/src/components/ui/TaskPreview.tsx
import type { TaskPreviewProps } from "@/types";
import { cn, getStatusColor, getStatusLabel } from "@/utils";

/**
 * Task preview component for displaying task lists
 * Converted from Vue TaskPreview.vue
 */
export function TaskPreview({
    tasks,
    limit = 5,
    onToggleTask,
}: TaskPreviewProps) {
    const displayTasks = tasks.slice(0, limit);

    if (displayTasks.length === 0) {
        return (
            <div className="text-center py-8 text-gray-500 dark:text-gray-400">
                <p>No tasks found</p>
            </div>
        );
    }

    return (
        <div className="space-y-2">
            {displayTasks.map((task) => (
                <div
                    key={task.id}
                    className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"
                >
                    <div className="flex items-center space-x-3">
                        <input
                            type="checkbox"
                            checked={task.completed}
                            onChange={() => onToggleTask(task.id)}
                            aria-label={task.title}
                            className={cn(
                                "w-5 h-5 rounded border flex items-center justify-center text-xs font-medium transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 appearance-none",
                                task.completed
                                    ? "bg-green-600 border-green-600 text-white"
                                    : "border-gray-300 dark:border-gray-600 hover:border-green-500",
                            )}
                        />
                        <div>
                            <p
                                className={cn(
                                    "text-sm font-medium text-gray-900 dark:text-white",
                                    task.completed && "line-through text-gray-500",
                                )}
                            >
                                {task.title}
                            </p>
                            <p className="text-xs text-gray-500 dark:text-gray-400 capitalize">
                                {task.priority} priority
                            </p>
                        </div>
                    </div>
                    <span
                        className={cn(
                            "inline-flex items-center px-2 py-1 rounded-full text-xs font-medium",
                            getStatusColor(task.status),
                        )}
                    >
                        {getStatusLabel(task.status)}
                    </span>
                </div>
            ))}

            {tasks.length > limit && (
                <div className="text-center py-2">
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                        +{tasks.length - limit} more tasks
                    </p>
                </div>
            )}
        </div>
    );
}

// legacy/frontend-vue/src/components/TaskPreview.vue
<script setup lang="ts">
import { CheckIcon } from '@heroicons/vue/24/solid';
import type { Task } from '../stores/tasks';

interface Props {
  tasks: Task[];
  limit?: number;
}

withDefaults(defineProps<Props>(), {
  limit: 5,
});

const emit = defineEmits<{
  toggleTask: [taskId: string];
}>();

const toggleTask = (taskId: string) => {
  emit('toggleTask', taskId);
};

const getStatusColor = (status: string) => {
  switch (status) {
    case 'todo':
      return 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300';
    case 'inProgress':
      return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300';
    case 'done':
      return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300';
    default:
      return 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300';
  }
};

const getStatusLabel = (status: string) => {
  switch (status) {
    case 'todo':
      return 'To Do';
    case 'inProgress':
      return 'In Progress';
    case 'done':
      return 'Done';
    default:
      return 'Unknown';
  }
};
</script>

<template>
  <div class="space-y-2">
    <div
      v-for="task in tasks.slice(0, limit)"
      :key="task.id"
      class="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"
    >
      <div class="flex items-center space-x-3">
        <button
          class="w-5 h-5 rounded-full border-2 flex items-center justify-center transition-colors duration-200"
          :class="
            task.completed
              ? 'bg-green-500 border-green-500 text-white'
              : 'border-gray-300 dark:border-gray-600 hover:border-green-500'
          "
          @click="toggleTask(task.id)"
        >
          <CheckIcon v-if="task.completed" class="w-3 h-3" />
        </button>
        <div>
          <p
            class="text-sm font-medium text-gray-900 dark:text-white"
            :class="{ 'line-through text-gray-500': task.completed }"
          >
            {{ task.title }}
          </p>
          <p class="text-xs text-gray-500 dark:text-gray-400 capitalize">
            {{ task.priority }} priority
          </p>
        </div>
      </div>
      <span
        class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium"
        :class="getStatusColor(task.status)"
      >
        {{ getStatusLabel(task.status) }}
      </span>
    </div>
    <div
      v-if="tasks.length === 0"
      class="text-center py-4 text-gray-500 dark:text-gray-400"
    >
      No tasks yet
    </div>
  </div>
</template>
