// apps/web/src/app/dashboard/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ActionButton } from "@/components/ui/ActionButton";
import { DashboardCard } from "@/components/ui/DashboardCard";
import HabitModal from "@/components/ui/HabitModal";
import { StatCard } from "@/components/ui/StatCard";
import { TaskModal } from "@/components/ui/TaskModal";
import { TaskPreview } from "@/components/ui/TaskPreview";
import { useHabitStore } from "@/contexts/HabitContext";
import { usePomodoroStore } from "@/contexts/PomodoroContext";
import { useTaskStore } from "@/contexts/TaskContext";
import type { CreateHabitRequest, CreateTaskRequest } from "@/types";

function DashboardContent() {
    const {
        todayTasks,
        completedToday,
        tasksByStatus,
        toggleTask,
        loadTasks,
        addTask,
    } = useTaskStore();
    const { totalStreaks, addHabit } = useHabitStore();
    const { todaySessionsCount } = usePomodoroStore();
    const router = useRouter();

    const [isTaskModalOpen, setIsTaskModalOpen] = useState(false);
    const [isHabitModalOpen, setIsHabitModalOpen] = useState(false);

    useEffect(() => {
        loadTasks();
    }, [loadTasks]);

    const handleCreateTask = (taskData: CreateTaskRequest) => {
        addTask(taskData);
    };

    const handleCreateHabit = (habitData: CreateHabitRequest) => {
        addHabit(habitData);
    };

    const handleStartFocus = () => {
        router.push("/pomodoro");
    };

    const weeklyProgress = Math.round(
        (completedToday / Math.max(todayTasks.length, 1)) * 100,
    );

    const getGreeting = () => {
        const hour = new Date().getHours();
        if (hour < 12) return "Good morning";
        if (hour < 18) return "Good afternoon";
        return "Good evening";
    };

    return (
        <div className="min-h-screen">
            {/* Hero Header */}
            <header className="mb-8">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="py-6">
                        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-3 animate-fade-in">
                            {getGreeting()}! 👋
                        </h1>
                        <p className="text-lg text-gray-600 dark:text-gray-400 animate-slide-up">
                            Here's your productivity overview for today
                        </p>
                    </div>
                </div>
            </header>

            <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8 pb-8">
                {/* Stats Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
                    <StatCard title="Tasks Completed" value={completedToday} icon="✅" />
                    <StatCard
                        title="Focus Sessions"
                        value={todaySessionsCount}
                        icon="🍅"
                    />
                    <StatCard title="Active Streaks" value={totalStreaks} icon="🔥" />
                    <StatCard
                        title="Weekly Progress"
                        value={`${weeklyProgress}%`}
                        icon="📊"
                    />
                </div>

                {/* Main Content Grid */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 md:gap-8">
                    {/* Quick Actions */}
                    <DashboardCard title="Quick Actions" className="lg:col-span-1">
                        <div className="space-y-3">
                            <ActionButton
                                icon="➕"
                                label="Create Task"
                                variant="primary"
                                onClick={() => setIsTaskModalOpen(true)}
                                className="w-full"
                            />
                            <ActionButton
                                icon="🍅"
                                label="Start Focus Session"
                                variant="secondary"
                                onClick={handleStartFocus}
                                className="w-full"
                            />
                            <ActionButton
                                icon="⚡"
                                label="Log Habit"
                                variant="secondary"
                                onClick={() => setIsHabitModalOpen(true)}
                                className="w-full"
                            />
                        </div>
                    </DashboardCard>

                    {/* Today's Tasks */}
                    <DashboardCard
                        title="Today's Tasks"
                        className="lg:col-span-2"
                        headerAction={
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300">
                                {todayTasks.length} {todayTasks.length === 1 ? "task" : "tasks"}
                            </span>
                        }
                    >
                        <TaskPreview
                            tasks={todayTasks}
                            limit={5}
                            onToggleTask={toggleTask}
                        />
                    </DashboardCard>
                </div>

                {/* Task Overview */}
                <DashboardCard title="Task Status Overview">
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                        <div className="text-center p-6 rounded-xl bg-gray-50 dark:bg-gray-700/30 transition-all hover:shadow-md">
                            <div className="text-4xl font-bold text-gray-700 dark:text-gray-300 mb-2 tabular-nums">
                                {tasksByStatus.todo.length}
                            </div>
                            <div className="text-sm font-medium text-gray-600 dark:text-gray-400 uppercase tracking-wide">
                                To Do
                            </div>
                            <div className="mt-2 w-full bg-gray-200 dark:bg-gray-600 rounded-full h-2">
                                <div
                                    className="bg-gray-500 dark:bg-gray-400 h-2 rounded-full"
                                    style={{ width: "100%" }}
                                />
                            </div>
                        </div>
                        <div className="text-center p-6 rounded-xl bg-blue-50 dark:bg-blue-900/20 transition-all hover:shadow-md">
                            <div className="text-4xl font-bold text-blue-600 dark:text-blue-400 mb-2 tabular-nums">
                                {tasksByStatus.inProgress.length}
                            </div>
                            <div className="text-sm font-medium text-blue-700 dark:text-blue-300 uppercase tracking-wide">
                                In Progress
                            </div>
                            <div className="mt-2 w-full bg-blue-200 dark:bg-blue-800/30 rounded-full h-2">
                                <div
                                    className="bg-blue-500 h-2 rounded-full"
                                    style={{ width: "100%" }}
                                />
                            </div>
                        </div>
                        <div className="text-center p-6 rounded-xl bg-green-50 dark:bg-green-900/20 transition-all hover:shadow-md">
                            <div className="text-4xl font-bold text-green-600 dark:text-green-400 mb-2 tabular-nums">
                                {tasksByStatus.done.length}
                            </div>
                            <div className="text-sm font-medium text-green-700 dark:text-green-300 uppercase tracking-wide">
                                Completed
                            </div>
                            <div className="mt-2 w-full bg-green-200 dark:bg-green-800/30 rounded-full h-2">
                                <div
                                    className="bg-green-500 h-2 rounded-full"
                                    style={{ width: "100%" }}
                                />
                            </div>
                        </div>
                    </div>
                </DashboardCard>
            </main>

            {/* Modals */}
            <TaskModal
                isOpen={isTaskModalOpen}
                onClose={() => setIsTaskModalOpen(false)}
                onSubmit={handleCreateTask}
            />
            <HabitModal
                isOpen={isHabitModalOpen}
                onClose={() => setIsHabitModalOpen(false)}
                onSubmit={handleCreateHabit}
            />
        </div>
    );
}

export default function DashboardPage() {
    return <DashboardContent />;
}

// legacy/frontend-vue/src/views/Dashboard.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { useTaskStore } from '../stores/tasks';
import { useHabitStore } from '../stores/habits';
import { usePomodoroStore } from '../stores/pomodoro';

import NavBar from '../components/NavBar.vue';
import StatCard from '../components/StatCard.vue';
import DashboardCard from '../components/DashboardCard.vue';
import ActionButton from '../components/ActionButton.vue';
import TaskPreview from '../components/TaskPreview.vue';
import PomodoroPreview from '../components/PomodoroPreview.vue';
import HabitPreview from '../components/HabitPreview.vue';

const taskStore = useTaskStore();
const habitStore = useHabitStore();
const pomodoroStore = usePomodoroStore();

const weeklyProgress = computed(() => {
  // Calculate weekly progress based on completed tasks and habits
  const tasksThisWeek = taskStore.tasks.filter(task => {
    const taskDate = new Date(task.updatedAt);
    const weekStart = new Date();
    weekStart.setDate(weekStart.getDate() - weekStart.getDay());
    return taskDate >= weekStart && task.status === 'done';
  }).length;

  const target = 20; // Weekly target
  return Math.min(Math.round((tasksThisWeek / target) * 100), 100);
});

const togglePomodoro = () => {
  if (pomodoroStore.isRunning) {
    pomodoroStore.pauseTimer();
  } else {
    pomodoroStore.startTimer();
  }
};

const resetPomodoro = () => {
  pomodoroStore.resetTimer();
};

onMounted(() => {
  taskStore.loadTasks();
  habitStore.loadHabits();
  pomodoroStore.loadSessions();
});
</script>

<template>
  <div class="dashboard-view">
    <NavBar />

    <main class="main-content">
      <!-- Dashboard Header -->
      <div class="dashboard-header">
        <h1>Welcome back!</h1>
        <p class="dashboard-subtitle">Here's your productivity overview</p>
      </div>

      <!-- Stats Grid -->
      <div class="stats-grid">
        <StatCard
          title="Tasks Completed Today"
          :value="taskStore.completedToday"
          icon="✅"
        />
        <StatCard
          title="Pomodoros Completed"
          :value="pomodoroStore.todaySessionsCount"
          icon="🍅"
        />
        <StatCard
          title="Total Streaks"
          :value="habitStore.totalStreaks"
          icon="🔥"
        />
        <StatCard title="Weekly Goal" :value="`${weeklyProgress}%`" icon="📊" />
      </div>

      <!-- Dashboard Grid -->
      <div class="dashboard-grid">
        <!-- Quick Actions -->
        <DashboardCard title="Quick Actions" class="quick-actions">
          <div class="action-buttons">
            <ActionButton
              icon="➕"
              label="Add Task"
              variant="primary"
              @click="$router.push('/tasks')"
            />
            <ActionButton
              icon="🍅"
              label="Start Focus"
              variant="secondary"
              @click="$router.push('/pomodoro')"
            />
            <ActionButton
              icon="⚡"
              label="Track Habit"
              variant="secondary"
              @click="$router.push('/habits')"
            />
          </div>
        </DashboardCard>

        <!-- Today's Tasks -->
        <DashboardCard title="Today's Tasks">
          <TaskPreview :tasks="taskStore.todayTasks.slice(0, 3)" />
          <button class="view-all-btn" @click="$router.push('/tasks')">
            View All Tasks
          </button>
        </DashboardCard>

        <!-- Focus Session -->
        <DashboardCard title="Focus Session">
          <PomodoroPreview
            :is-running="pomodoroStore.isRunning"
            :current-time="pomodoroStore.currentTime"
            :session-type="pomodoroStore.sessionType"
            :progress="pomodoroStore.progress"
            :formatted-time="pomodoroStore.formattedTime"
            :today-sessions-count="pomodoroStore.todaySessionsCount"
            @toggle-timer="togglePomodoro"
            @reset-timer="resetPomodoro"
          />
        </DashboardCard>

        <!-- Habit Progress -->
        <DashboardCard title="Habit Progress">
          <HabitPreview :habits="habitStore.todayProgress.slice(0, 3)" />
          <button class="view-all-btn" @click="$router.push('/habits')">
            View All Habits
          </button>
        </DashboardCard>
      </div>
    </main>
  </div>
</template>

<style scoped>
.dashboard-view {
  min-height: 100vh;
  background: var(--bg-primary);
}

.main-content {
  padding: 2rem;
  max-width: 1400px;
  margin: 0 auto;
}

.dashboard-header {
  margin-bottom: 2rem;
}

.dashboard-header h1 {
  font-size: 2.5rem;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 0.5rem;
}

.dashboard-subtitle {
  font-size: 1.125rem;
  color: var(--text-secondary);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.dashboard-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 1.5rem;
}

.action-buttons {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.view-all-btn {
  width: 100%;
  padding: 0.75rem;
  background: var(--bg-secondary);
  border: 1px solid var(--border-color);
  border-radius: 8px;
  color: var(--text-secondary);
  font-size: 0.875rem;
  cursor: pointer;
  transition: all 0.2s ease;
  margin-top: 1rem;
}

.view-all-btn:hover {
  background: var(--bg-tertiary);
  color: var(--text-primary);
}

@media (max-width: 768px) {
  .main-content {
    padding: 1rem;
  }

  .dashboard-header h1 {
    font-size: 2rem;
  }

  .stats-grid {
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
  }

  .dashboard-grid {
    grid-template-columns: 1fr;
    gap: 1rem;
  }
}
</style>
